'''Observe public profile operations generated by the website itself.'''

import asyncio
import contextlib
import json
from typing import Any
from urllib.parse import SplitResult, urlsplit

from playwright.async_api import Page, Response, Route

from scrape_exchange.twitch.endpoints import GRAPHQL_URL, PROFILE_BASE_URL
from scrape_exchange.twitch.settings import TwitchScraperSettings
from scrape_exchange.twitch.twitch_creator import TwitchCreator
from scrape_exchange.twitch.twitch_error_classification import (
    ProfileExtractionError,
    ProfileRateLimitError,
    ProfileUnavailableError,
)
from scrape_exchange.twitch.twitch_profile_extractor import extract_profile
from scrape_exchange.twitch.twitch_rate_limiter import (
    TwitchCallType,
    TwitchRateLimiter,
)

_OPERATIONS: set[str] = {
    'ChannelShell', 'ChannelAvatar', 'ChannelRoot_AboutPanel',
    'ChannelPanels',
}
_CORE_OPERATIONS: set[str] = {
    'ChannelShell', 'ChannelRoot_AboutPanel', 'ChannelPanels',
}
_MAX_RESPONSE_BYTES: int = 2_000_000
_MAX_RESPONSES: int = 64


def _batch(value: object) -> list:
    if isinstance(value, list):
        return value
    return [value] if isinstance(value, dict) else []


def _operation(request: object, username: str) -> str | None:
    if not isinstance(request, dict):
        return None
    name: object = request.get('operationName')
    variables: object = request.get('variables')
    if (
        not isinstance(name, str) or name not in _OPERATIONS
        or not isinstance(variables, dict)
    ):
        return None
    if name == 'ChannelPanels' and isinstance(variables.get('id'), str):
        return 'ChannelPanels'
    login: object = variables.get('login', variables.get('channelLogin'))
    if isinstance(login, str) and login.casefold() == username:
        return str(name)
    return None


def profile_operations(requests: object, username: str) -> list[str]:
    return [
        name for request in _batch(requests)
        if (name := _operation(request, username)) is not None
    ]


def select_profile_responses(
    requests: object, responses: object, username: str,
) -> list[dict[str, Any]]:
    '''Keep only paired responses for this profile's public operations.'''
    reqs: list = _batch(requests)
    resps: list = _batch(responses)
    if len(reqs) != len(resps):
        return []
    selected: list[dict[str, Any]] = []
    for request, response in zip(reqs, resps):
        name: str | None = _operation(request, username)
        if not name or not isinstance(response, dict):
            continue
        if name == 'ChannelPanels':
            data: object = response.get('data')
            user: object = data.get('user') if isinstance(data, dict) else None
            if not isinstance(user, dict) or (
                str(user.get('login', '')).casefold() != username
                or user.get('id') != request['variables'].get('id')
            ):
                continue
        selected.append(response)
    return selected


def _request_json(raw: str | None) -> object:
    try:
        return json.loads(raw or '')
    except (ValueError, RecursionError):
        return None


def _check_response(payload: dict[str, Any]) -> None:
    data: object = payload.get('data')
    if isinstance(data, dict):
        user: object = data.get('userOrError')
        if isinstance(user, dict) and user.get('__typename') in (
            'UserDoesNotExist', 'UserDoesNotExistError',
        ):
            raise ProfileUnavailableError('Website reports no such user')
    errors: object = payload.get('errors')
    if isinstance(errors, list):
        for error in errors:
            if not isinstance(error, dict):
                continue
            extensions: object = error.get('extensions')
            if isinstance(extensions, dict) and extensions.get('code') in (
                'RATE_LIMITED', 'FORBIDDEN', 'UNAUTHENTICATED',
            ):
                raise ProfileRateLimitError('Anonymous profile request denied')


async def fetch_profile(
    page: Page, username: str, settings: TwitchScraperSettings,
    limiter: TwitchRateLimiter, proxy: str,
) -> TwitchCreator:
    '''Fetch within a deadline and always detach listeners and routes.

    Navigation permission is acquired by the caller before claiming work.
    Each browser-generated profile HTTP request acquires DATA permission.
    No requests are replayed and no client IDs or authentication supplied.
    '''
    expected: SplitResult = urlsplit(GRAPHQL_URL)
    payloads: list[object] = []
    pending: set[asyncio.Task[None]] = set()
    failures: list[Exception] = []
    completed: set[str] = set()
    ready: asyncio.Event = asyncio.Event()
    active: bool = True

    def is_profile_endpoint(url: str) -> bool:
        parsed: SplitResult = urlsplit(url)
        return (
            parsed.scheme, parsed.netloc, parsed.path,
        ) == (expected.scheme, expected.netloc, expected.path)

    async def gate(route: Route) -> None:
        try:
            if route.request.resource_type in ('media', 'image', 'font'):
                await route.abort()
                return
            if is_profile_endpoint(route.request.url) and profile_operations(
                _request_json(route.request.post_data), username,
            ):
                await limiter.acquire(TwitchCallType.DATA, proxy=proxy)
            await route.continue_()
        except asyncio.CancelledError:
            raise
        except Exception as exc:  # noqa: BLE001 - propagate callback failures
            failures.append(exc)
            ready.set()
            with contextlib.suppress(Exception):
                await route.abort()

    async def capture(response: Response, requests: object) -> None:
        try:
            if response.status in (401, 403, 429):
                raise ProfileRateLimitError('Profile HTTP request blocked')
            if response.status >= 500:
                raise ProfileExtractionError('Profile HTTP request failed')
            size: str = response.headers.get('content-length', '0')
            if size.isdigit() and int(size) > _MAX_RESPONSE_BYTES:
                return
            raw: bytes = await response.body()
            if len(raw) > _MAX_RESPONSE_BYTES:
                return
            data: object = _request_json(raw.decode('utf-8'))
            selected: list[dict[str, Any]] = select_profile_responses(
                requests, data, username,
            )
            for item in selected:
                _check_response(item)
            if selected:
                payloads.extend(selected[:_MAX_RESPONSES - len(payloads)])
                completed.update(profile_operations(requests, username))
                if _CORE_OPERATIONS <= completed:
                    ready.set()
        except asyncio.CancelledError:
            raise
        except Exception as exc:  # noqa: BLE001 - propagate callback failures
            failures.append(exc)
            ready.set()

    def on_response(response: Response) -> None:
        if not active or not is_profile_endpoint(response.url):
            return
        requests: object = _request_json(response.request.post_data)
        if not profile_operations(requests, username):
            return
        if len(pending) >= 16 or len(payloads) >= _MAX_RESPONSES:
            return
        task: asyncio.Task[None] = asyncio.create_task(
            capture(response, requests),
        )
        pending.add(task)
        task.add_done_callback(pending.discard)

    page.on('response', on_response)
    try:
        async with asyncio.timeout(settings.creator_profile_timeout_seconds):
            await page.route('**/*', gate)
            response: Response | None = await page.goto(
                f'{PROFILE_BASE_URL}/{username}/about',
                wait_until='domcontentloaded',
                timeout=settings.creator_profile_timeout_seconds * 1000,
            )
            if response and response.status in (401, 403, 429):
                raise ProfileRateLimitError('Profile navigation blocked')
            if response and response.status >= 400:
                # An HTTP error may be a proxy response, not a user verdict.
                raise ProfileExtractionError('Profile navigation failed')
            with contextlib.suppress(asyncio.TimeoutError):
                await asyncio.wait_for(
                    ready.wait(), settings.creator_data_wait_seconds,
                )
            if failures:
                raise failures[0]
            if urlsplit(page.url).path.startswith(('/login', '/challenge')):
                raise ProfileRateLimitError('Anonymous access requires login')
            html: str = await page.content()
            return extract_profile(
                payloads, html, username, PROFILE_BASE_URL,
            )
    finally:
        active = False
        page.remove_listener('response', on_response)
        for task in pending:
            task.cancel()
        await asyncio.gather(*pending, return_exceptions=True)
        with contextlib.suppress(Exception):
            await page.unroute('**/*', gate)
