#!/usr/bin/env python3
'''
One-shot operator script: reconcile an external JSONL DB export
with the Redis identity maps (creator_map, handle_map).

Delta semantics: missing-from-JSONL is not a signal to delete.
Non-destructive fills apply silently. Casing-only differences
where one side is all-lowercase resolve silently to the mixed-
case variant. True handle conflicts (Redis and JSONL each hold
a different non-null handle for the same channel_id) are
**deferred to the channel scraper**: the importer enqueues the
``channel_id`` into the Redis channel scrape queue (priority)
so the scraper re-fetches and writes the authoritative handle
back through its normal pipeline. Same treatment for
:class:`InconsistentIdentityError` cases where ``bind()``
refuses because the handle is already claimed by a different
``channel_id``.

Usage::

    uv run python -m tools.yt_import_channel_export \
        --external-jsonl /path/to/db-export.jsonl
'''

import argparse
import asyncio
import json
import logging
import sys
from dataclasses import dataclass
from typing import IO

import redis.asyncio as aioredis

from scrape_exchange.channel_scrape_queue import (
    ChannelScrapeQueue,
    ChannelScrapeQueueSettings,
    RedisChannelScrapeQueue,
)
from scrape_exchange.creator_map import RedisCreatorMap
from scrape_exchange.handle_map import RedisHandleMap
from scrape_exchange.youtube.channel_identity import (
    ChannelIdentityStore,
    InconsistentIdentityError,
)
from scrape_exchange.youtube.settings import (
    YouTubeScraperSettings,
)


_LOGGER: logging.Logger = logging.getLogger(__name__)


@dataclass(slots=True)
class ImportSummary:
    lines_read: int = 0
    filled: int = 0
    no_change: int = 0
    casing_auto_resolved: int = 0
    deferred_to_scraper: int = 0
    skipped_inconsistent: int = 0
    parse_errors: int = 0


@dataclass(slots=True)
class _Conflict:
    '''A destructive handle disagreement deferred to the scraper.'''
    channel_id: str
    jsonl_handle: str
    redis_handle: str


def _casing_only_winner(
    redis_handle: str, jsonl_handle: str,
) -> str | None:
    '''
    Return the mixed-case variant when *redis_handle* and
    *jsonl_handle* differ only in casing AND exactly one of them
    is all-lowercase. Returns ``None`` for substantive
    differences or for case-ambiguous pairs (both lowercase, or
    both mixed-case but unequal).

    Mirrors the creator-intended-casing rule used elsewhere in
    the channel-identity codebase: when the lowercase variant
    looks autogenerated and the mixed-case variant looks
    creator-supplied, the latter wins automatically.
    '''
    if redis_handle.lower() != jsonl_handle.lower():
        return None
    redis_is_lower: bool = redis_handle == redis_handle.lower()
    jsonl_is_lower: bool = jsonl_handle == jsonl_handle.lower()
    if redis_is_lower and not jsonl_is_lower:
        return jsonl_handle
    if jsonl_is_lower and not redis_is_lower:
        return redis_handle
    return None


async def run_import(
    jsonl_in: IO[str],
    *,
    store: ChannelIdentityStore,
    queue: ChannelScrapeQueue,
) -> ImportSummary:
    '''Read JSONL lines from *jsonl_in* and reconcile with *store*.

    Two passes:

    1. **Scan** — apply non-destructive fills silently. Apply
       casing-only resolutions silently (the mixed-case variant
       wins; see :func:`_casing_only_winner`). Buffer true
       handle conflicts (Redis and JSONL both hold a non-null
       handle for the same channel_id but they disagree).
    2. **Defer** — for each buffered conflict, enqueue the
       channel_id into *queue* at priority=True. The channel
       scraper picks these up and writes the authoritative
       value back through its normal pipeline.

    :class:`InconsistentIdentityError` raised by ``bind()`` also
    enqueues both channel_ids involved.
    '''
    summary: ImportSummary = ImportSummary()
    conflicts: list[_Conflict] = []
    raw_line: str
    for raw_line in jsonl_in:
        line: str = raw_line.strip()
        if not line:
            continue
        summary.lines_read += 1
        record: dict
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            _LOGGER.warning(
                'Skipping unparseable JSONL line',
                extra={
                    'line': line[:200],
                    'reason': str(exc),
                },
            )
            summary.parse_errors += 1
            continue
        await _scan_one(
            record, store, conflicts, summary, queue,
        )

    if conflicts:
        _LOGGER.info(
            f'Deferring {len(conflicts)} handle conflict(s) '
            f'to the channel scraper via queue',
        )
        for conflict in conflicts:
            await _enqueue_priority(
                queue, conflict.channel_id,
            )
            summary.deferred_to_scraper += 1
    return summary


async def _scan_one(
    record: dict,
    store: ChannelIdentityStore,
    conflicts: list[_Conflict],
    summary: ImportSummary,
    queue: ChannelScrapeQueue,
) -> None:
    '''Classify a single record: fill, no-op, casing auto-resolve,
    or buffer as a destructive conflict.'''
    channel_id: str | None = record.get('channel_id')
    handle: str | None = record.get('channel_handle')
    if not channel_id or not handle:
        return
    existing: str | None = (
        await store.creator_map.get(channel_id)
    )
    if existing is None:
        if await _safe_bind(
            store, channel_id, handle, summary, queue,
        ):
            summary.filled += 1
        return
    if existing == handle:
        summary.no_change += 1
        return
    winner: str | None = _casing_only_winner(existing, handle)
    if winner is not None:
        if winner != existing and not await _safe_bind(
            store, channel_id, winner, summary, queue,
        ):
            return
        summary.casing_auto_resolved += 1
        return
    conflicts.append(_Conflict(
        channel_id=channel_id,
        jsonl_handle=handle,
        redis_handle=existing,
    ))


async def _safe_bind(
    store: ChannelIdentityStore,
    channel_id: str,
    handle: str,
    summary: ImportSummary,
    queue: ChannelScrapeQueue,
) -> bool:
    '''Call ``store.bind`` and swallow
    :class:`InconsistentIdentityError`. On failure, log the
    conflict and enqueue **both** channel_ids involved at
    priority so the scraper re-fetches both and the authoritative
    state lands via its normal pipeline. Bumps
    ``summary.skipped_inconsistent``. Returns True iff bind
    succeeded.
    '''
    try:
        await store.bind(channel_id, handle)
        return True
    except InconsistentIdentityError as exc:
        _LOGGER.warning(
            f'Skipping inconsistent handle binding: '
            f'channel_id={channel_id!r} '
            f'handle={handle!r} reason={exc}',
        )
        await _enqueue_priority(queue, channel_id)
        # Enqueue the OTHER channel_id too — handle_map says it
        # currently owns this handle, but we don't trust either
        # claim; let the scraper resolve which is authoritative.
        other_id: str | None = await store.handle_map.get(handle)
        if other_id and other_id != channel_id:
            await _enqueue_priority(queue, other_id)
        summary.skipped_inconsistent += 1
        return False


async def _enqueue_priority(
    queue: ChannelScrapeQueue,
    channel_id: str,
) -> None:
    '''Enqueue *channel_id* into *queue* at priority so the
    channel scraper resolves the authoritative handle via its
    normal pipeline.'''
    try:
        await queue.enqueue_scheduled(
            channel_id,
            source='importer',
            priority=True,
        )
    except Exception as exc:
        _LOGGER.warning(
            f'Failed to enqueue priority channel: '
            f'channel_id={channel_id!r} reason={exc}',
        )


async def _main(args: argparse.Namespace) -> int:
    # Disable pydantic-settings CLI parsing so our local argparse
    # owns sys.argv (it already consumed --external-jsonl). Without
    # this, the base Settings re-scans sys.argv and rejects the
    # unknown flag.
    settings: YouTubeScraperSettings = YouTubeScraperSettings(
        _cli_parse_args=False,
    )
    queue_settings: ChannelScrapeQueueSettings = (
        ChannelScrapeQueueSettings()
    )
    # RedisCreatorMap owns its connection via DSN.
    # RedisHandleMap and RedisChannelScrapeQueue share a client.
    client: aioredis.Redis = aioredis.from_url(
        settings.redis_dsn, decode_responses=True,
    )
    try:
        store: ChannelIdentityStore = ChannelIdentityStore(
            creator_map=RedisCreatorMap(
                settings.redis_dsn, 'youtube',
            ),
            handle_map=RedisHandleMap(client),
        )
        queue: RedisChannelScrapeQueue = RedisChannelScrapeQueue(
            client, queue_settings,
        )
        with open(  # NOSONAR — operator script, one-shot sync read
            args.external_jsonl, 'r', encoding='utf-8',
        ) as fh:
            summary: ImportSummary = await run_import(
                fh,
                store=store,
                queue=queue,
            )
    finally:
        await client.aclose()
    _LOGGER.info(
        f'import complete: '
        f'lines_read={summary.lines_read} '
        f'filled={summary.filled} '
        f'no_change={summary.no_change} '
        f'casing_auto_resolved={summary.casing_auto_resolved} '
        f'deferred_to_scraper={summary.deferred_to_scraper} '
        f'skipped_inconsistent={summary.skipped_inconsistent} '
        f'parse_errors={summary.parse_errors}',
    )
    return 0


def main(argv: list[str] | None = None) -> int:
    logging.basicConfig(level=logging.INFO)
    parser: argparse.ArgumentParser = argparse.ArgumentParser(
        description=(
            'Reconcile an external JSONL DB export with'
            ' the Redis identity maps.'
        ),
    )
    parser.add_argument(
        '--external-jsonl',
        required=True,
        help='Path to the JSONL DB export to reconcile.',
    )
    args: argparse.Namespace = parser.parse_args(argv)
    return asyncio.run(_main(args))


if __name__ == '__main__':
    raise SystemExit(main(sys.argv[1:]))
